# based on https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
  # Directory (relative to root of your repo) that contains the deploy-ready
  # HTML files and assets.
  publish = "public/"
